exports.seats_array = async (show_id) => {
    return [{
        show_id: show_id,
        seat_row: "A",
        seat_number: "01",
        type: "U",
        status: false,
        price: 100,
    },
    {
        show_id: show_id,
        seat_row: "A",
        seat_number: "02",
        type: "U",
        status: false,
        price: 100,
    },
    {
        show_id: show_id,
        seat_row: "A",
        seat_number: "03",
        type: "U",
        status: false,
        price: 100,
    },
    {
        show_id: show_id,
        seat_row: "A",
        seat_number: "04",
        type: "U",
        status: false,
        price: 100,
    },
    {
        show_id: show_id,
        seat_row: "A",
        seat_number: "05",
        type: "U",
        status: false,
        price: 100,
    },
    {
        show_id: show_id,
        seat_row: "B",
        seat_number: "01",
        type: "U",
        status: false,
        price: 100,
    },
    {
        show_id: show_id,
        seat_row: "B",
        seat_number: "02",
        type: "U",
        status: false,
        price: 100,
    },
    {
        show_id: show_id,
        seat_row: "B",
        seat_number: "03",
        type: "U",
        status: false,
        price: 100,
    },
    {
        show_id: show_id,
        seat_row: "B",
        seat_number: "04",
        type: "U",
        status: false,
        price: 100,
    },
    {
        show_id: show_id,
        seat_row: "B",
        seat_number: "05",
        type: "U",
        status: false,
        price: 100,
    }
    ]
}